version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 8Jsc7nUXyG  # Update to the FreeSQLDatabase.com root password
      MYSQL_DATABASE: sql5665576  # Update to the database name (dcbapp-qa)
      MYSQL_USER: sql5665576  # Update to the database user (app_user)
      MYSQL_PASSWORD: 8Jsc7nUXyG  # Update to the user's password (12345678)

  spring-app:
    image: openjdk:17-jdk-slim
    container_name: spring_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql5.freesqldatabase.com:3306/sql5665576  # Update to the FreeSQLDatabase.com details
      SPRING_DATASOURCE_USERNAME: sql5665576  # Update to the database user (app_user)
      SPRING_DATASOURCE_PASSWORD: 8Jsc7nUXyG  # Update to the user's password (12345678)
    depends_on:
      - mysql

