version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: W@2915djkq#
      MYSQL_DATABASE: dcbapp-qa
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    image: openjdk:17-jdk-slim
    container_name: spring_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dcbapp-qa
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
